[project]

name = "chatbot-frontend"
revision = "1.0"

[default]

# No provider defined here.
# Will refer to  ~/.config/secretspec/config.toml

[profiles]

[profiles.default]

AI_SECRET = { description = "Shared token between Chatbot Frontend and Backend", required = true }
