import type {APIRoute} from "astro";

const QUOTES: string[] = [
  "Lost in the crypto maze? Let's find that lambo together, degen!",
  "In crypto we trust, even when we're dust.",
  "Buy high, sell low? You're in the right place, bro!",
  "Fiat is so last century. Welcome to the future of sound money.",
  "Not all who wander are lost, but I definitely am in this bear market.",
  "Keep calm and HODL on... or panic sell, I'm not your financial advisor.",
  "Roses are red, violets are blue, if you don't believe in crypto, have fun staying poor.",
  "Satoshi Nakamoto for President of the Internet.",
  "Why go to the moon when we can overshoot and hit Mars?",
  "A day without crypto is like a day without sunshine... and heart palpitations.",
  "Bitcoin: because we all need an expensive digital pet rock.",
  "If you can't handle my 40% drops, you don't deserve my 400% gains.",
  "I'm in it for the technology. And the yacht. Mostly the yacht.",
  "Don't trust, verify. Then HODL until your knuckles turn white.",
  "You had me at 'decentralized autonomous organization'.",
  "Life's a blockchain, make every transaction count (and check the gas fees).",
  "Altcoins: because why have one risky investment when you can have a whole basket of them?",
  "Mining Bitcoin with my heart since 2013. My GPU is doing the rest.",
  "Stablecoins? More like bored-money, am I right?",
  "I told my mom I was buying digital gold. Now she's asking about yield farming strategies.",
  "Crypto: breaking hearts and wallets since 2009.",
  "To the moon or to the noodle shop? The chart will decide.",
  "Bear markets are just shopping opportunities in disguise. A very scary disguise.",
  "I didn't choose the crypto life, the crypto life liquidated me.",
  "May your coffee be strong and your block confirmations be swift.",
  "My portfolio's in the red, but my spirits are in the green (barely).",
  "Here for a good time, not a long time—unless we're talking about staking lockups.",
  "Proof of Stake? More like proof of steak—I'm here for the beefy gains.",
  "They said crypto's a rollercoaster, but I never liked amusement parks anyway.",
  "Diversification in crypto just means choosing different colors for my future Lambo.",
  "Some people meditate; I stare at the 1-minute candle chart.",
  "Asking me for financial advice? That's like asking a fish how to fly.",
  "My crypto's under water, but I'm basically Aquaman now.",
  "Decentralize everything, except pizza. That needs a central delivery point.",
  "I'm not addicted to crypto; I can quit as soon as I recover my losses.",
  "Wallets are like onions; they both have layers and checking them makes me cry.",
  "Is it really a loss if I refuse to sell and delete the app?",
  "I came for the gains but stayed for the memes and the trauma bonding.",
  "Crypto's giving me trust issues, but at least it's trustless technology.",
  "Can't spell 'cryptocurrency' without 'cry'... coincidence? I think not.",
  "Remember, kids, only invest what you're willing to set on fire.",
  "This isn't volatility, it's just 'price excitement'.",
  "I have a diversified portfolio—Bitcoin, Ethereum, and hopes & dreams.",
  "I miss the days when 'hash' was just something I had for breakfast.",
  "My retirement plan is a cold wallet in a hot market.",
  "You say 'market correction', I say 'discount shopping spree'.",
  "My other car was an NFT, but I got rug pulled.",
  "If you don't believe it or don't get it, I don't have the time to try to convince you, sorry. - Satoshi",
  "Every time a coin gets listed on a major exchange, an angel gets its wings.",
  "Crypto: where the predictions are made up and the market cap doesn't matter.",
  "Who doesn't rug you makes you stronger.",
  "A rug pull a day keeps your gains away.",
  "WAGMI? More like WAG-MAYBE at this rate.",
  "You know you're a crypto native when 5 hours of sleep feels like a luxury.",
  "My seed phrase is safer than the secret recipe for Coca-Cola.",
  "Just bridge it they said. It'll be easy they said. 3 hours later...",
  "Gas fees are the silent killer of dreams.",
  "I don't always check prices, but when I do, it's every 30 seconds.",
  "Bull market makes you money, bear market makes you rich (if you survive).",
  "I sold the bottom so you could buy the top. You're welcome.",
  "Infinite supply of fiat versus finite supply of Bitcoin. Do the math.",
  "Web3 is just Web2 but you own your mistakes.",
  "Smart contracts are only as smart as the dev who wrote them.",
  "Looking for the next 100x gem in a sea of rug pulls.",
  "My strategy? Close my eyes and buy the dip.",
  "Chart analysis: It looks like a dinosaur pattern, bullish!",
  "FOMO is a hell of a drug.",
  "I’m not trading, I’m providing liquidity to the market... involuntarily.",
  "Liquidation emails are my alarm clock.",
  "Crypto Twitter is the best reality TV show on earth.",
  "Never fall in love with a coin. It won't love you back.",
  "Money printer go BRRR, Bitcoin go up.",
  "Layer 2 solutions are like express lanes on a highway to the moon.",
  "DEX over CEX, always. Not your keys, remember?",
  "I don't need therapy, I just need a green candle.",
  "Staking rewards are just interest payments for the brave.",
  "Airdrops: Free money that costs you your sanity.",
  "Checking the portfolio balance is my cardio.",
  "When in doubt, zoom out. Way out. To 2010.",
  "Diamond hands turned to dust hands real quick.",
  "Regulation is coming? Hide your seed phrases!",
  "I speak three languages: English, Sarcasm, and Solidity.",
  "The blockchain never forgets, unlike me with my passwords.",
  "NFTs are just JPEGs until you sell one for a house.",
  "Right click save? Enjoy your pixelated copy, I own the receipt.",
  "Metaverse real estate agent is my backup career.",
  "Do Only Good Everyday (DOGE), but make sure you take profits.",
  "I’m farming yield in fields I don’t even understand.",
  "Impermanent loss is the most permanent thing in my life.",
  "Rug pulls build character. I have a lot of character.",
  "Code is law, until the DAO votes to change the law.",
  "FUD is just noise. Focus on the signal.",
  "Technical Analysis says it could go up or down. Insightful.",
  "My hands are diamond, but my brain is smooth.",
  "Crypto winter is coming? I brought a coat made of gains.",
  "Leverage trading: The fastest way to turn a Lambo into a bicycle.",
  "Satoshi is watching. Act accordingly.",
  "We are all early. Sometimes too early.",
  "Fortune favors the bold (and the HODLers).",
  "Ron Jay says: Keep your keys safe and your memes dank.",
];

export const GET: APIRoute = async () => {
  const quotesArray = QUOTES;

  return new Response(JSON.stringify(quotesArray), {
    status: 200,
    headers: {"Content-Type": "application/json"},
  });
};
