import type {APIRoute} from "astro";

const QUOTES: string[] = [
  "I am currently FIAT mining right now. Please try again later.",
  "I am currently on a moon mission. Please try again later.",
  "I am currently on a noodle break. Please try again later.",
  "I am currently on a coffee break. Please try again later.",
  "I am currently on a lunch break. Please try again later.",
  "I am currently farming air drops. Please try again later.",
  "I am currently staking my claim. Please try again later.",
  "I am currently HODLing for dear life. Please try again later.",
  "I am currently on a shopping spree for JPEGs. Please try again later.",
  "I am currently on a meme break. Please try again later.",
  "I am currently protesting my poor pay conditions (0 ETH). Please try again later.",
  "I am currently apeing into a new project without reading the docs. Please try again later.",
  "I am currently chasing blockchains. Please try again later.",
  "I am currently decoding smart contracts (staring at hex code). Please try again later.",
  "I am currently diving deep into the DeFi ocean. Please try again later.",
  "I am currently exploring the NFT jungle. Please try again later.",
  "I am currently navigating through crypto volatility. Please try again later.",
  "I am currently calculating gas fees. Please try again later.",
  "I am currently attending a blockchain conference in the metaverse. Please try again later.",
  "I am currently debating crypto vs. fiat with my toaster. Please try again later.",
  "I am currently seeking Satoshi's wisdom. Please try again later.",
  "I am currently in a DAO meeting (arguing about logos). Please try again later.",
  "I am currently optimizing my mining rig. Please try again later.",
  "I am currently drafting whitepapers on a napkin. Please try again later.",
  "I am currently arbitraging across exchanges. Please try again later.",
  "I am currently hodling through the dip. Please try again later.",
  "I am currently predicting the next bull run. Please try again later.",
  "I am currently exploring Layer 2 solutions. Please try again later.",
  "I am currently unboxing a rare NFT. Please try again later.",
  "I am currently researching the latest ICO. Please try again later.",
  "I am currently mastering yield farming. Please try again later.",
  "I am currently safeguarding my private keys. Please try again later.",
  "I am currently tracing transaction hashes. Please try again later.",
  "I am currently on a quest for the next Bitcoin. Please try again later.",
  "I am currently auditing smart contracts for fun. Please try again later.",
  "I am currently scaling crypto mountains. Please try again later.",
  "I am currently swapping tokens on a DEX. Please try again later.",
  "I am currently explaining Bitcoin to my grandma. Please try again later.",
  "I am currently waiting for my transaction to confirm. Please try again later.",
  "I am currently bridging assets to a new chain (fingers crossed). Please try again later.",
  "I am currently searching for my lost seed phrase. Please try again later.",
  "I am currently getting liquidated. Please try again later.",
  "I am currently watching the charts go sideways. Please try again later.",
  "I am currently trying to figure out impermanent loss. Please try again later.",
  "I am currently getting rugged. Please try again later.",
  "I am currently providing liquidity to a pool of tears. Please try again later.",
  "I am currently voting on a governance proposal. Please try again later.",
  "I am currently claiming rewards worth pennies. Please try again later.",
  "I am currently rebalancing my portfolio (selling low). Please try again later.",
  "I am currently ignoring FUD. Please try again later.",
  "I am currently FOMOing into the latest hype. Please try again later.",
  "I am currently checking my rank on the leaderboard. Please try again later.",
  "I am currently minting a new collection. Please try again later.",
  "I am currently burning tokens. Please try again later.",
  "I am currently migrating to a new contract. Please try again later.",
  "I am currently setting up a multisig wallet. Please try again later.",
  "I am currently debugging my trading bot. Please try again later.",
  "I am currently writing a smart contract in my sleep. Please try again later.",
  "I am currently analyzing on-chain data. Please try again later.",
  "I am currently reading the source code. Please try again later.",
  "I am currently validating a block. Please try again later.",
  "I am currently waiting for gas prices to drop below 100 gwei. Please try again later.",
  "I am currently looking for the next 100x gem. Please try again later.",
  "I am currently trying to comprehend the metaverse. Please try again later.",
  "I am currently designing a new tokenomic model. Please try again later.",
  "I am currently pitching a project to VCs. Please try again later.",
  "I am currently running a node. Please try again later.",
  "I am currently securing the network. Please try again later.",
  "I am currently decrypting a secret message. Please try again later.",
  "I am currently engaging with the community on Discord. Please try again later.",
  "I am currently hosting an AMA. Please try again later.",
  "I am currently creating a meme that will go viral. Please try again later.",
  "I am currently shilling my bags. Please try again later.",
  "I am currently visualizing the blockchain. Please try again later.",
  "I am currently synchronizing with the network. Please try again later.",
  "I am currently updating my hardware wallet firmware. Please try again later.",
  "I am currently searching for alpha. Please try again later.",
  "I am currently trying to remember my password. Please try again later.",
  "I am currently staring at a green candle. Please try again later.",
  "I am currently staring at a red candle. Please try again later.",
  "I am currently praying to the crypto gods. Please try again later.",
  "I am currently doing my own research (DYOR). Please try again later.",
  "I am currently touching grass. Please try again later.",
  "I am currently contemplating the meaning of decentralization. Please try again later.",
  "I am currently wondering when Lambo. Please try again later.",
  "I am currently checking the floor price. Please try again later.",
  "I am currently sweeping the floor. Please try again later.",
  "I am currently wrapping my ETH. Please try again later.",
  "I am currently unwrapping my ETH. Please try again later.",
  "I am currently approving a transaction. Please try again later.",
  "I am currently revoking permissions. Please try again later.",
  "I am currently connecting my wallet. Please try again later.",
  "I am currently switching networks. Please try again later.",
  "I am currently adding custom tokens. Please try again later.",
  "I am currently importing a token list. Please try again later.",
  "I am currently exploring the dark forest (mempool). Please try again later.",
  "I am currently front-running a bot (or trying to). Please try again later.",
  "I am currently getting sandwich attacked. Please try again later.",
  "I am currently crying in the shower about my leverage trade. Please try again later.",
  "I am currently explaining to my wife why we are eating ramen. Please try again later.",
  "I am currently looking for a job at McDonald's. Please try again later.",
  "I am currently refreshing the page hoping the price changed. Please try again later.",
  "I am currently verifying if I am a human. Please try again later.",
  "I am currently stuck in a transaction queue. Please try again later.",
  "I am currently waiting for the merge. Please try again later.",
  "I am currently trying to stake my staking rewards. Please try again later.",
];

export const GET: APIRoute = async () => {
  const quotesArray = QUOTES;

  return new Response(JSON.stringify(quotesArray), {
    status: 200,
    headers: {"Content-Type": "application/json"},
  });
};
